window.qq = window.qq || {};
qq.maps = qq.maps || {};
window.soso || (window.soso = qq);
soso.maps || (soso.maps = qq.maps);
(function () {
    var conneturl = "http://" + window.location.host + "/TVMap/transfer?";
    qq.maps.__load = function (apiLoad) {
        delete qq.maps.__load;
        apiLoad([["2.3.14", "4F5BZ-ZQSCP-FM6DI-VT2TU-HDRU7-OWBBU", 0], [conneturl + "http://open.map.qq.com/", "apifiles/2/3/14/mods/", conneturl + "http://open.map.qq.com/apifiles/2/3/14/theme/", true], [1, 18, 34.519469, 104.461761, 4], [1453803904792, conneturl + "http://pr.map.qq.com/pingd", conneturl + "http://pr.map.qq.com/pingd"], [conneturl + "http://apis.map.qq.com/jsapi", conneturl + "http://apikey.map.qq.com/mkey/index.php/mkey/check", conneturl + "http://sv.map.qq.com/xf", conneturl + "http://sv.map.qq.com/boundinfo", conneturl + "http://sv.map.qq.com/rarp", conneturl + "http://search.map.qq.com/", conneturl + "http://routes.map.qq.com/"], [[null, [conneturl + "http://p0.map.gtimg.com/maptilesv3", conneturl + "http://p1.map.gtimg.com/maptilesv3", conneturl + "http://p2.map.gtimg.com/maptilesv3", conneturl + "http://p3.map.gtimg.com/maptilesv3"], "png", [256, 256], 1, 19, "", true, false], [null, [conneturl + "http://m0.map.gtimg.com/hwap", conneturl + "http://m1.map.gtimg.com/hwap", conneturl + "http://m2.map.gtimg.com/hwap", conneturl + "http://m3.map.gtimg.com/hwap"], "png", [256, 256], 4, 18, "104", false, false], [null, [conneturl + "http://p0.map.gtimg.com/sateTiles", conneturl + "http://p1.map.gtimg.com/sateTiles", conneturl + "http://p2.map.gtimg.com/sateTiles", conneturl + "http://p3.map.gtimg.com/sateTiles"], "jpg", [256, 256], 1, 19, "", false, false], [null, [conneturl + "http://p0.map.gtimg.com/sateTranTilesv3", conneturl + "http://p1.map.gtimg.com/sateTranTilesv3", conneturl + "http://p2.map.gtimg.com/sateTranTilesv3", conneturl + "http://p3.map.gtimg.com/sateTranTilesv3"], "png", [256, 256], 1, 19, "", false, false], [null, [conneturl + "http://sv0.map.qq.com/road/", conneturl + "http://sv1.map.qq.com/road/", conneturl + "http://sv2.map.qq.com/road/", conneturl + "http://sv3.map.qq.com/road/"], "png", [256, 256], 1, 19, "", false, false], [null, [conneturl + "http://rtt2a.map.qq.com/live/", conneturl + "http://rtt2b.map.qq.com/live/", conneturl + "http://rtt2c.map.qq.com/live/"], "png", [256, 256], 1, 19, "", false, false], null, null, null], [conneturl + "http://s.map.qq.com/TPano/v1.1.1/TPano.js", conneturl + "http://map.qq.com/", ""]], loadScriptTime);
    };
    var loadScriptTime = (new Date).getTime();
})();